#+TITLE: Agricultura.org

* Dicas

- Existem receitas de culinaria (neste caso de pao) cujo segredo é nao colocar o sal diretamente com o fermento, o segredo é misturar o fermento e a farinha primeiro, depois o sal
- Ao cortar hortela ou outras ervas com caules rijos, cujas folhas sao aproveitas mas os caules nao, mesmo assim ha utilidade nos caules. O canal 24 Kitchen atou os caules e usou como aromatizante do caldo que estava a fazer. Ferveu na agua, no final da cozedura é que mandou fora
- Iogurte (por exemplo iogurte natural) para substituir Natas
- Cheddar é um tipo de queijo ideal para hamburgers, derrete-se ao ser colocado por cima da carne

* Receitas ToDo:
Yakisoba (do restaurante Nood)
Vinho (pelo menos 1 litro na vida). Fazer de raiz
pao indiano: https://youtu.be/z1O8cfAyaz4?si=JEXpm5xdwDtxfNTe
petit gateau https://www.youtube.com/watch?v=z-s0dNKnanM
* Compostagem
exemplo: https://youtu.be/MnpUWPUXGu4?si=3GnT87LSsHBISxfb

* Lista de coisas a NAO ADQUIRIR
nil. Coisas que nao se gosta ou coisas marcadas para nao comprar/adquirir
* Dicionario
o que é...

Curcuma == Acafrao

Gratinado?
Bechamel de arroz?
o que e azeite virgem e extra virgem?

