#+TITLE: bolas de batata frita

Hashtags: #yammy-only #yammy #forno #estacao-ano-x #preco-x #pessoas-n #tempo-x #rapido #mt-facil #doses-1
source: https://youtube.com/shorts/25VJcRqMa9A?si=0L3K9TZB9pnbmNL0 
img: 

Ingredientes:
   @ [ 300 gr ] batatas
   @ [  15 gr ] farinha (peneirada)
   @ [   qb   ] sal fino
   @ [   qb   ] pimenta
   @ [   qb   ] oleo alimentar (para fritar)

Prep:
   --1-- Cozer
         (existe receita de pure de batata no livro da yammy)

         Cozer batatas (30 min)

   --2-- Fazer o puré
   	 Escorrer as batatas, nao convem ter agua nenhuma.
	 Esborrachar/Misturar a batata, farinha, sal e pimenta até ficar num puré homogenio

   --3-- Alizar
         Fazer bolas com essa massa (usando farinha nas maos para nao se colar muito
	 As bolas nao deve ser muito grandes, senao nao fritam por dentro

   --4-- Panar
         Antes de irem fritar no oleo, as bolas tem de rebolar num recipuente com farinha peneirada para que depois nao se colem ao fundo da fritadeira

   --5-- Fritar
         Levar a frigideira ate ficar dourado (temperatura no maximo, para dourar rapido e ensopar pouco de oleo

Servir:
   - Servir morno 
   - Doses: X pessoas
   - Peso final: X kg

Materiais:
 - Espumadeira      (para filtrar a agua das batatas e filtrar as bolas fritas do oleo)
 - Papel absorvente (para as bolas fritas)
 - Passador         (para pneirar a farinha)

Duraçao: 
   Pre-Preparacao:  x min
   Preparacao:      x min
   Lavar materiais: x min
   total: 

Dicas: 
 - 

Relatorio das ultimas prep:
 - Tentativa 1: 560g de batata no como da yammy. Com 100 gramas de agua
                borboleta inserida, 30 min, vel 1, 100 graus.
                Foi juntado 50g de farinha e a borboleta ficou em esforco, juntou-se mais 25g de farinha e ficou com demasiado esforco. Acabou-se de misturar com uma espatula
                Adicionado sal fino
                Dessa mistura que foi retirada para um prato, foram feitas bolas enroladas com a mao enquanto exiatia uma panela com oleo alimentar a aquecer no fogao.
                O oleo do fogao, na altura de fritar as batatas nao pode estar demasiado quente, senao o conteudo da batata sai para fora.... no fogao eletrico o nivel 5 de 6 foi muito, vou experimentar para a proxima com o 4 de 6

 - Tentativa 2: 1070g de batata
                1000g agua
                30 min, 100 C.; vel 1 + borboleta
                escorrida a agua
                1 min + vel 4 + borboleta
                100g farinha (peneirada de preferencia)
                2 min + vel 2 + borboleta
                35 g farinha, repetido
                faltou o sal
                a farinha nao chegou (agarra-se muito as maos). Se fosse menos quntidade, voltava a por na maquina com mais farinha. Ou entao é necessario farinha à parte como os pasteleiros, espalhar nas maos antes de fazer as bolinhas
                Foi colocado a fritar, mas nao correu bem. As bolas podem-se colar ao fundo e podem-se colar umas as outras. Neste caso, as bolas colaram-se umas as outras porque quanfo comecaram a flutuar tambem espandiram em tamanho e nao couberam na frigideira sem estar apertadas... Como elas tem a propriedade de se colar, nao ficaram sequer em bolas
                A batata a fritar tambem estava muito mole que nem dava para lhes mexer com uma colher. Provavelmente porque foi cozinho com muita agua

  - Tentativa 3: Desta vez, antes de colocar as bolas no oleo, rebolei muito bem as bolas em farinha peneirada (as bolas ja nao se desfizeram)
                 Para a proxima: experimentar fritar na temperatura maxima 6 de 6 (fogao eletrico) em vez de 3 de 6 (pois o objetivo é dourar a batata, nao é ensopar com oleo)
                 Talvez seja da temperatura baixa: Ficaram douradas, mas nao estaladicas
